POSIX Shared Memory Data Structures: shm_simd::SimdArray< TableType > Class Template Reference
shm_simd::SimdArray< TableType > Class Template Reference
Helper class for SIMD operations on shm_array.
#include <shm_simd_utils.h>
Public Member Functions
SimdArray (shm_array< float, TableType > &array)
float sum () const noexcept
float min () const noexcept
float max () const noexcept
void scale (float factor) noexcept
float dot (const shm_array< float, TableType > &other) const noexcept
Detailed Description
template<typename TableType = shm_table>
class shm_simd::SimdArray< TableType >
Helper class for SIMD operations on shm_array.
Template Parameters
TableType Metadata table type
Example:
shm_array<float> data(shm, "data", 10000);
SimdArray simd(data);
float sum = simd.sum();
simd.scale(2.0f);
Definition at line 313 of file shm_simd_utils.h.
Constructor & Destructor Documentation
SimdArray()
template<typename TableType = shm_table> shm_simd::SimdArray< TableType >::SimdArray (shm_array< float, TableType > & array) inline explicit
Definition at line 318 of file shm_simd_utils.h.
Member Function Documentation
dot()
template<typename TableType = shm_table> float shm_simd::SimdArray< TableType >::dot (const shm_array< float, TableType > & other) const inline noexcept
Definition at line 336 of file shm_simd_utils.h.
References shm_array< T, TableType >::data(), shm_simd::dot_product(), and shm_array< T, TableType >::size().
max()
template<typename TableType = shm_table> float shm_simd::SimdArray< TableType >::max () const inline noexcept
Definition at line 328 of file shm_simd_utils.h.
References shm_array< T, TableType >::data(), shm_simd::max_float(), and shm_array< T, TableType >::size().
Referenced by main().
min()
template<typename TableType = shm_table> float shm_simd::SimdArray< TableType >::min () const inline noexcept
Definition at line 324 of file shm_simd_utils.h.
References shm_array< T, TableType >::data(), shm_simd::min_float(), and shm_array< T, TableType >::size().
Referenced by main().
scale()
template<typename TableType = shm_table> void shm_simd::SimdArray< TableType >::scale (float factor) inline noexcept
Definition at line 332 of file shm_simd_utils.h.
References shm_array< T, TableType >::data(), shm_simd::scale_floats(), and shm_array< T, TableType >::size().
sum()
template<typename TableType = shm_table> float shm_simd::SimdArray< TableType >::sum () const inline noexcept
Definition at line 320 of file shm_simd_utils.h.
References shm_array< T, TableType >::data(), shm_array< T, TableType >::size(), and shm_simd::sum_floats().
Referenced by main().
The documentation for this class was generated from the following file:
include/shm_simd_utils.h