# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1507/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1507/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spinoza/github/beta/zeroipc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spinoza/github/beta/zeroipc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/snap/cmake/1507/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/snap/cmake/1507/bin/cpack --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1487/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1507/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/snap/cmake/1507/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/snap/cmake/1507/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/snap/cmake/1507/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/snap/cmake/1507/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/snap/cmake/1507/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/snap/cmake/1507/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spinoza/github/beta/zeroipc/CMakeFiles /home/spinoza/github/beta/zeroipc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spinoza/github/beta/zeroipc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_table

# Build rule for target.
test_table: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_table
.PHONY : test_table

# fast build rule for target.
test_table/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_table.dir/build.make cpp/CMakeFiles/test_table.dir/build
.PHONY : test_table/fast

#=============================================================================
# Target rules for targets named test_memory

# Build rule for target.
test_memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_memory
.PHONY : test_memory

# fast build rule for target.
test_memory/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_memory.dir/build.make cpp/CMakeFiles/test_memory.dir/build
.PHONY : test_memory/fast

#=============================================================================
# Target rules for targets named test_array

# Build rule for target.
test_array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_array
.PHONY : test_array

# fast build rule for target.
test_array/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_array.dir/build.make cpp/CMakeFiles/test_array.dir/build
.PHONY : test_array/fast

#=============================================================================
# Target rules for targets named test_queue

# Build rule for target.
test_queue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_queue
.PHONY : test_queue

# fast build rule for target.
test_queue/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_queue.dir/build.make cpp/CMakeFiles/test_queue.dir/build
.PHONY : test_queue/fast

#=============================================================================
# Target rules for targets named test_stack

# Build rule for target.
test_stack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_stack
.PHONY : test_stack

# fast build rule for target.
test_stack/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_stack.dir/build.make cpp/CMakeFiles/test_stack.dir/build
.PHONY : test_stack/fast

#=============================================================================
# Target rules for targets named test_lockfree_comprehensive

# Build rule for target.
test_lockfree_comprehensive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lockfree_comprehensive
.PHONY : test_lockfree_comprehensive

# fast build rule for target.
test_lockfree_comprehensive/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_lockfree_comprehensive.dir/build.make cpp/CMakeFiles/test_lockfree_comprehensive.dir/build
.PHONY : test_lockfree_comprehensive/fast

#=============================================================================
# Target rules for targets named test_stress

# Build rule for target.
test_stress: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_stress
.PHONY : test_stress

# fast build rule for target.
test_stress/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_stress.dir/build.make cpp/CMakeFiles/test_stress.dir/build
.PHONY : test_stress/fast

#=============================================================================
# Target rules for targets named test_edge_cases

# Build rule for target.
test_edge_cases: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_edge_cases
.PHONY : test_edge_cases

# fast build rule for target.
test_edge_cases/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_edge_cases.dir/build.make cpp/CMakeFiles/test_edge_cases.dir/build
.PHONY : test_edge_cases/fast

#=============================================================================
# Target rules for targets named test_aba_problem

# Build rule for target.
test_aba_problem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_aba_problem
.PHONY : test_aba_problem

# fast build rule for target.
test_aba_problem/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_aba_problem.dir/build.make cpp/CMakeFiles/test_aba_problem.dir/build
.PHONY : test_aba_problem/fast

#=============================================================================
# Target rules for targets named test_table_stress

# Build rule for target.
test_table_stress: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_table_stress
.PHONY : test_table_stress

# fast build rule for target.
test_table_stress/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_table_stress.dir/build.make cpp/CMakeFiles/test_table_stress.dir/build
.PHONY : test_table_stress/fast

#=============================================================================
# Target rules for targets named test_memory_boundaries

# Build rule for target.
test_memory_boundaries: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_memory_boundaries
.PHONY : test_memory_boundaries

# fast build rule for target.
test_memory_boundaries/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_memory_boundaries.dir/build.make cpp/CMakeFiles/test_memory_boundaries.dir/build
.PHONY : test_memory_boundaries/fast

#=============================================================================
# Target rules for targets named test_failure_recovery

# Build rule for target.
test_failure_recovery: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_failure_recovery
.PHONY : test_failure_recovery

# fast build rule for target.
test_failure_recovery/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_failure_recovery.dir/build.make cpp/CMakeFiles/test_failure_recovery.dir/build
.PHONY : test_failure_recovery/fast

#=============================================================================
# Target rules for targets named test_new_structures

# Build rule for target.
test_new_structures: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_new_structures
.PHONY : test_new_structures

# fast build rule for target.
test_new_structures/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_new_structures.dir/build.make cpp/CMakeFiles/test_new_structures.dir/build
.PHONY : test_new_structures/fast

#=============================================================================
# Target rules for targets named test_codata

# Build rule for target.
test_codata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_codata
.PHONY : test_codata

# fast build rule for target.
test_codata/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_codata.dir/build.make cpp/CMakeFiles/test_codata.dir/build
.PHONY : test_codata/fast

#=============================================================================
# Target rules for targets named test_cli_tool

# Build rule for target.
test_cli_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cli_tool
.PHONY : test_cli_tool

# fast build rule for target.
test_cli_tool/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_cli_tool.dir/build.make cpp/CMakeFiles/test_cli_tool.dir/build
.PHONY : test_cli_tool/fast

#=============================================================================
# Target rules for targets named test_coverage_improvement

# Build rule for target.
test_coverage_improvement: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_coverage_improvement
.PHONY : test_coverage_improvement

# fast build rule for target.
test_coverage_improvement/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_coverage_improvement.dir/build.make cpp/CMakeFiles/test_coverage_improvement.dir/build
.PHONY : test_coverage_improvement/fast

#=============================================================================
# Target rules for targets named test_semaphore

# Build rule for target.
test_semaphore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_semaphore
.PHONY : test_semaphore

# fast build rule for target.
test_semaphore/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_semaphore.dir/build.make cpp/CMakeFiles/test_semaphore.dir/build
.PHONY : test_semaphore/fast

#=============================================================================
# Target rules for targets named test_barrier

# Build rule for target.
test_barrier: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_barrier
.PHONY : test_barrier

# fast build rule for target.
test_barrier/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_barrier.dir/build.make cpp/CMakeFiles/test_barrier.dir/build
.PHONY : test_barrier/fast

#=============================================================================
# Target rules for targets named test_latch

# Build rule for target.
test_latch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_latch
.PHONY : test_latch

# fast build rule for target.
test_latch/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_latch.dir/build.make cpp/CMakeFiles/test_latch.dir/build
.PHONY : test_latch/fast

#=============================================================================
# Target rules for targets named test_once

# Build rule for target.
test_once: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_once
.PHONY : test_once

# fast build rule for target.
test_once/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_once.dir/build.make cpp/CMakeFiles/test_once.dir/build
.PHONY : test_once/fast

#=============================================================================
# Target rules for targets named test_event

# Build rule for target.
test_event: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_event
.PHONY : test_event

# fast build rule for target.
test_event/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_event.dir/build.make cpp/CMakeFiles/test_event.dir/build
.PHONY : test_event/fast

#=============================================================================
# Target rules for targets named test_mutex

# Build rule for target.
test_mutex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mutex
.PHONY : test_mutex

# fast build rule for target.
test_mutex/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_mutex.dir/build.make cpp/CMakeFiles/test_mutex.dir/build
.PHONY : test_mutex/fast

#=============================================================================
# Target rules for targets named test_monitor

# Build rule for target.
test_monitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_monitor
.PHONY : test_monitor

# fast build rule for target.
test_monitor/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_monitor.dir/build.make cpp/CMakeFiles/test_monitor.dir/build
.PHONY : test_monitor/fast

#=============================================================================
# Target rules for targets named test_rwlock

# Build rule for target.
test_rwlock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_rwlock
.PHONY : test_rwlock

# fast build rule for target.
test_rwlock/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_rwlock.dir/build.make cpp/CMakeFiles/test_rwlock.dir/build
.PHONY : test_rwlock/fast

#=============================================================================
# Target rules for targets named test_signal

# Build rule for target.
test_signal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_signal
.PHONY : test_signal

# fast build rule for target.
test_signal/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_signal.dir/build.make cpp/CMakeFiles/test_signal.dir/build
.PHONY : test_signal/fast

#=============================================================================
# Target rules for targets named zeroipc

# Build rule for target.
zeroipc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zeroipc
.PHONY : zeroipc

# fast build rule for target.
zeroipc/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/zeroipc.dir/build.make cpp/CMakeFiles/zeroipc.dir/build
.PHONY : zeroipc/fast

#=============================================================================
# Target rules for targets named test_fast

# Build rule for target.
test_fast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fast
.PHONY : test_fast

# fast build rule for target.
test_fast/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_fast.dir/build.make cpp/CMakeFiles/test_fast.dir/build
.PHONY : test_fast/fast

#=============================================================================
# Target rules for targets named test_default

# Build rule for target.
test_default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_default
.PHONY : test_default

# fast build rule for target.
test_default/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_default.dir/build.make cpp/CMakeFiles/test_default.dir/build
.PHONY : test_default/fast

#=============================================================================
# Target rules for targets named test_ci

# Build rule for target.
test_ci: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ci
.PHONY : test_ci

# fast build rule for target.
test_ci/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_ci.dir/build.make cpp/CMakeFiles/test_ci.dir/build
.PHONY : test_ci/fast

#=============================================================================
# Target rules for targets named test_all

# Build rule for target.
test_all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_all
.PHONY : test_all

# fast build rule for target.
test_all/fast:
	$(MAKE) $(MAKESILENT) -f cpp/CMakeFiles/test_all.dir/build.make cpp/CMakeFiles/test_all.dir/build
.PHONY : test_all/fast

#=============================================================================
# Target rules for targets named benchmark_queue

# Build rule for target.
benchmark_queue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_queue
.PHONY : benchmark_queue

# fast build rule for target.
benchmark_queue/fast:
	$(MAKE) $(MAKESILENT) -f cpp/benchmarks/CMakeFiles/benchmark_queue.dir/build.make cpp/benchmarks/CMakeFiles/benchmark_queue.dir/build
.PHONY : benchmark_queue/fast

#=============================================================================
# Target rules for targets named benchmark_stack

# Build rule for target.
benchmark_stack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_stack
.PHONY : benchmark_stack

# fast build rule for target.
benchmark_stack/fast:
	$(MAKE) $(MAKESILENT) -f cpp/benchmarks/CMakeFiles/benchmark_stack.dir/build.make cpp/benchmarks/CMakeFiles/benchmark_stack.dir/build
.PHONY : benchmark_stack/fast

#=============================================================================
# Target rules for targets named benchmark_array

# Build rule for target.
benchmark_array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_array
.PHONY : benchmark_array

# fast build rule for target.
benchmark_array/fast:
	$(MAKE) $(MAKESILENT) -f cpp/benchmarks/CMakeFiles/benchmark_array.dir/build.make cpp/benchmarks/CMakeFiles/benchmark_array.dir/build
.PHONY : benchmark_array/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test_all"
	@echo "... test_ci"
	@echo "... test_default"
	@echo "... test_fast"
	@echo "... benchmark_array"
	@echo "... benchmark_queue"
	@echo "... benchmark_stack"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... test_aba_problem"
	@echo "... test_array"
	@echo "... test_barrier"
	@echo "... test_cli_tool"
	@echo "... test_codata"
	@echo "... test_coverage_improvement"
	@echo "... test_edge_cases"
	@echo "... test_event"
	@echo "... test_failure_recovery"
	@echo "... test_latch"
	@echo "... test_lockfree_comprehensive"
	@echo "... test_memory"
	@echo "... test_memory_boundaries"
	@echo "... test_monitor"
	@echo "... test_mutex"
	@echo "... test_new_structures"
	@echo "... test_once"
	@echo "... test_queue"
	@echo "... test_rwlock"
	@echo "... test_semaphore"
	@echo "... test_signal"
	@echo "... test_stack"
	@echo "... test_stress"
	@echo "... test_table"
	@echo "... test_table_stress"
	@echo "... zeroipc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

