site_name: ZeroIPC Documentation
site_description: High-performance cross-language shared memory IPC library
site_author: ZeroIPC Contributors
site_url: https://zeroipc.io

repo_name: zeroipc/zeroipc
repo_url: https://github.com/yourusername/zeroipc
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: zeroipc
      repo: zeroipc
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/zeroipc
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/zeroipc/

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
      - Basic Concepts: getting-started/concepts.md
  - Tutorial:
      - tutorial/index.md
      - Your First Shared Memory: tutorial/first-shared-memory.md
      - Working with Arrays: tutorial/arrays.md
      - Using Queues and Stacks: tutorial/queues-stacks.md
      - Reactive Streams: tutorial/streams.md
      - Synchronization Primitives: tutorial/synchronization.md
      - Advanced Patterns: tutorial/advanced-patterns.md
  - CLI Tool:
      - cli/index.md
      - Basic Commands: cli/basic-commands.md
      - Virtual Filesystem: cli/virtual-filesystem.md
      - Structure Inspection: cli/structure-inspection.md
      - Monitoring and Debugging: cli/monitoring.md
  - API Reference:
      - api/index.md
      - C++ API:
          - Memory & Table: api/cpp/memory.md
          - Data Structures: api/cpp/data-structures.md
          - Synchronization: api/cpp/synchronization.md
          - Codata Structures: api/cpp/codata.md
      - Python API:
          - Memory & Table: api/python/memory.md
          - Data Structures: api/python/data-structures.md
          - Synchronization: api/python/synchronization.md
          - Codata Structures: api/python/codata.md
      - C API:
          - Overview: api/c/overview.md
  - Architecture:
      - architecture/index.md
      - Binary Format: architecture/binary-format.md
      - Design Principles: architecture/design-principles.md
      - Lock-Free Implementation: architecture/lock-free.md
      - Memory Layout: architecture/memory-layout.md
      - Testing Strategy: architecture/testing.md
  - Examples:
      - examples/index.md
      - Cross-Language Communication: examples/cross-language.md
      - Producer-Consumer: examples/producer-consumer.md
      - Sensor Data Sharing: examples/sensor-data.md
      - Reactive Processing: examples/reactive-processing.md
      - Real-Time Analytics: examples/analytics.md
  - Best Practices:
      - best-practices/index.md
      - Performance Tips: best-practices/performance.md
      - Common Pitfalls: best-practices/pitfalls.md
      - Type Safety: best-practices/type-safety.md
      - Error Handling: best-practices/error-handling.md
      - Testing Applications: best-practices/testing.md
  - Advanced Topics:
      - advanced/index.md
      - Codata Programming: advanced/codata.md
      - Lock-Free Patterns: advanced/lock-free-patterns.md
      - Memory Ordering: advanced/memory-ordering.md
      - Custom Structures: advanced/custom-structures.md
  - Contributing:
      - contributing/index.md
      - Development Setup: contributing/setup.md
      - Adding Language Support: contributing/new-language.md
      - Testing Guidelines: contributing/testing.md

copyright: Copyright &copy; 2024 ZeroIPC Contributors
