POSIX Shared Memory Data Structures: examples/simd_simulation.cpp File Reference
simd_simulation.cpp File Reference
Example of SIMD-optimized particle simulation using shared memory.
#include <iostream>
#include <chrono>
#include <random>
#include <iomanip>
#include "posix_shm.h"
#include "shm_array.h"
#include "shm_simd_utils.h"
Classes
struct ParticleSystemSoA
Functions
void initialize_particles (ParticleSystemSoA &particles)
void update_physics_scalar (ParticleSystemSoA &particles, float dt)
void update_physics_simd (ParticleSystemSoA &particles, float dt)
float calculate_kinetic_energy_scalar (ParticleSystemSoA &particles)
float calculate_kinetic_energy_simd (ParticleSystemSoA &particles)
int main ()
Variables
constexpr size_t NUM_PARTICLES = 100000
constexpr size_t ITERATIONS = 100
Detailed Description
Example of SIMD-optimized particle simulation using shared memory.
Author
Alex Towell
Demonstrates:
SIMD operations on shared memory arrays
Structure of Arrays (SoA) layout for better vectorization
Cache-friendly access patterns
Performance comparison vs scalar operations
Definition in file simd_simulation.cpp.
Function Documentation
calculate_kinetic_energy_scalar()
float calculate_kinetic_energy_scalar (ParticleSystemSoA & particles)
Definition at line 160 of file simd_simulation.cpp.
References ParticleSystemSoA::mass, NUM_PARTICLES, ParticleSystemSoA::vx, ParticleSystemSoA::vy, and ParticleSystemSoA::vz.
Referenced by main().
calculate_kinetic_energy_simd()
float calculate_kinetic_energy_simd (ParticleSystemSoA & particles)
Definition at line 174 of file simd_simulation.cpp.
References shm_array< T, TableType >::data(), shm_simd::dot_product(), ParticleSystemSoA::mass, NUM_PARTICLES, shm_simd::scale_floats(), shm_span< T, ShmType >::shm, ParticleSystemSoA::vx, ParticleSystemSoA::vy, ParticleSystemSoA::vz, and ParticleSystemSoA::x.
Referenced by main().
initialize_particles()
void initialize_particles (ParticleSystemSoA & particles)
Definition at line 45 of file simd_simulation.cpp.
References ParticleSystemSoA::ax, ParticleSystemSoA::ay, ParticleSystemSoA::az, ParticleSystemSoA::mass, NUM_PARTICLES, ParticleSystemSoA::vx, ParticleSystemSoA::vy, ParticleSystemSoA::vz, ParticleSystemSoA::x, ParticleSystemSoA::y, and ParticleSystemSoA::z.
Referenced by main().
main()
int main ()
Definition at line 208 of file simd_simulation.cpp.
References calculate_kinetic_energy_scalar(), calculate_kinetic_energy_simd(), shm_array< T, TableType >::data(), initialize_particles(), shm_simd::is_aligned(), ITERATIONS, shm_simd::SimdArray< TableType >::max(), shm_simd::SimdArray< TableType >::min(), NUM_PARTICLES, shm_simd::SimdArray< TableType >::sum(), update_physics_scalar(), update_physics_simd(), ParticleSystemSoA::vx, and ParticleSystemSoA::x.
update_physics_scalar()
void update_physics_scalar (ParticleSystemSoA & particles, float dt)
Definition at line 70 of file simd_simulation.cpp.
References ParticleSystemSoA::ax, ParticleSystemSoA::ay, ParticleSystemSoA::az, NUM_PARTICLES, ParticleSystemSoA::vx, ParticleSystemSoA::vy, ParticleSystemSoA::vz, ParticleSystemSoA::x, ParticleSystemSoA::y, and ParticleSystemSoA::z.
Referenced by main().
update_physics_simd()
void update_physics_simd (ParticleSystemSoA & particles, float dt)
Definition at line 91 of file simd_simulation.cpp.
References ParticleSystemSoA::ax, ParticleSystemSoA::ay, ParticleSystemSoA::az, NUM_PARTICLES, ParticleSystemSoA::vx, ParticleSystemSoA::vy, ParticleSystemSoA::vz, ParticleSystemSoA::x, ParticleSystemSoA::y, and ParticleSystemSoA::z.
Referenced by main().
Variable Documentation
ITERATIONS
constexpr size_t ITERATIONS = 100 constexpr
Definition at line 25 of file simd_simulation.cpp.
Referenced by main().
NUM_PARTICLES
constexpr size_t NUM_PARTICLES = 100000 constexpr
Definition at line 24 of file simd_simulation.cpp.
Referenced by calculate_kinetic_energy_scalar(), calculate_kinetic_energy_simd(), initialize_particles(), main(), update_physics_scalar(), and update_physics_simd().